### ISSUE TITLE
Pictures cannot be paginated

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle.js#1319]
**Describe the bug**
Pictures cannot be paginated

**To Reproduce**

[bug](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%09%3Chead%3E%20%09%09%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%09%09%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%09%09%3Ctitle%3Etable%3C/title%3E%20%20%09%09%3Cstyle%3E%20%09%09%09img%20%7B%20%09%09%09%09width:%20500px;%20%09%09%09%09height:%20500px;%20%09%09%09%7D%20%20%09%09%09@page%20%7B%20%09%09%09%09size:%20A4%20portrait;%20%09%09%09%09margin:%2030px;%20%09%09%09%7D%20%20%09%09%09.mate-pro%20%7B%20%09%09%09%09page:%20matePro;%20%09%09%09%7D%20%20%09%09%09.header%20%7B%20%09%09%09%09content:%20element(HeaderRunning);%20%09%09%09%7D%20%09%09%09@page%20matePro%20%7B%20%09%09%09%09@top-center%20%7B%20%09%09%09%09%09content:%20element(HeaderRunning);%20%09%09%09%09%7D%20%09%09%09%7D%20%09%09%3C/style%3E%20%09%3C/head%3E%20%20%09%3Cbody%3E%20%09%09%3Csection%20class=%22mate-pro%22%3E%20%09%09%09%3Cheader%20class=%22header%22%3Eheader%20total%208%20pictures%3C/header%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%3C/section%3E%20%09%3C/body%3E%20%3C/html%3E&f=epubcfi(/2!/4/2/4))
[picture-bug.txt](https://github.com/vivliostyle/vivliostyle.js/files/15245532/picture-bug.txt)

**Comment by MurakamiShinyu** [comment]
@EnochGao Thanks for the bug report! I am investigating the problem.

For now, you can avoid the problem by adding the following style:

```css
img {
  display: block;
}
```

or

```css
body {
  widows: 1;
  orphans: 1;
}
```

It seems that the widows/orphans control is broken when the paragraph consists of inline images only.



By the way, I found a trivial problem in your style:

```css
      .header {
        content: element(HeaderRunning);
      }
      @page matePro {
        @top-center {
          content: element(HeaderRunning);
        }
      }
```

I think this should be:

```css
      .header {
        position: running(HeaderRunning);
      }
      @page matePro {
        @top-center {
          content: element(HeaderRunning);
        }
      }
```

**Comment by EnochGao** [comment]
This is a great project, thank you for your answer, it was my mistake, I tried your method, this problem is solved

**Comment by MurakamiShinyu** [comment]
This issue is still unresolved because what I suggested for avoid the problem were only workarounds for the bug. There should be page break opportunity between pictures in this original case.

**Comment by EnochGao** [comment]
> This issue is still unresolved because what I suggested for avoid the problem were only workarounds for the bug. There should be page break opportunity between pictures in this original case.

👍👍👍👍👍👍👍

**Comment by jiang0112** [comment]
When images are laid out in flex, images cannot be paginated。
[bug](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%09%3Chead%3E%20%09%09%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%09%09%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%09%09%3Ctitle%3Etable%3C/title%3E%20%20%09%09%3Cstyle%3E%20%09%09%09.img-content%20%7B%20%09%09%09%09display:%20flex;%20%09%09%09%09flex-direction:%20row;%20%20%20%20%20%09%09%09%09%20justify-content:%20space-between;%20%20%20%20%20%20%09%09%09%09flex-wrap:%20wrap;%20%09%09%09%7D%20%09%09%09img%20%7B%20%09%09%09%09width:%20300px;%20%09%09%09%09height:%20300px;%20%09%09%09%09display:%20block%20%09%09%09%7D%20%20%09%09%09@page%20%7B%20%09%09%09%09size:%20A4%20portrait;%20%09%09%09%09margin:%2030px;%20%09%09%09%7D%20%20%09%09%09.mate-pro%20%7B%20%09%09%09%09page:%20matePro;%20%09%09%09%7D%20%20%09%09%09.header%20%7B%20%09%09%09%09position:%20running(HeaderRunning);%20%09%09%09%7D%20%09%09%09@page%20matePro%20%7B%20%09%09%09%09@top-center%20%7B%20%09%09%09%09%09content:%20element(HeaderRunning);%20%09%09%09%09%7D%20%09%09%09%7D%20%09%09%3C/style%3E%20%09%3C/head%3E%20%20%09%3Cbody%3E%20%09%09%3Csection%20class=%22mate-pro%22%3E%20%09%09%09%3Cheader%20class=%22header%22%3Eheader%20total%208%20pictures%3C/header%3E%20%09%09%09%3Cdiv%20class=%22img-content%22%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%09%3Cimg%20%09%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09%09/%3E%20%09%09%09%3C/div%3E%20%09%09%09%20%09%09%3C/section%3E%20%09%3C/body%3E%20%3C/html%3E&f=epubcfi(/2!/4/2/4))

**Comment by jiang0112** [comment]
When a `table `cell `td`contains an  `img`, even after setting display: block; on the image, pagination issues persist. 
[bug](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%09%3Chead%3E%20%09%09%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%09%09%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%09%09%3Ctitle%3Etable%3C/title%3E%20%09%09%3Cscript%20src=%22../../../dist/paged.polyfill.js%22%3E%3C/script%3E%20%20%09%09%3Cstyle%3E%20%09%09%09.base-footer%20%7B%20%09%09%09%09text-transform:%20uppercasse;%20%09%09%09%09font-size:%2012px;%20%09%09%09%7D%20%20%09%09%09.base-header%20%7B%20%09%09%09%09height:%20100px;%20%09%09%09%09text-align:%20start;%20%09%09%09%09position:%20relative;%20%09%09%09%7D%20%20%09%09%09.base-title%20%7B%20%09%09%09%09position:%20absolute;%20%09%09%09%09left:%20295px;%20%09%09%09%09top:%2038px;%20%09%09%09%09font-size:%2016px;%20%09%09%09%09font-weight:%20500;%20%09%09%09%09line-height:%2019px;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20%7B%20%09%09%09%09width:%20100%25;%20%09%09%09%09border-collapse:%20collapse;%20%09%09%09%09border:%201px%20solid%20%23dcdcdc;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20thead%20tr%20%7B%20%09%09%09%09background:%20%23ebedf1;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20thead%20tr%20th%20%7B%20%09%09%09%09text-align:%20center;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20tr,%20%09%09%09.base-evaluation%20td%20%7B%20%09%09%09%09break-inside:%20avoid;%20%09%09%09%7D%20%20%09%09%09.base-evaluation%20th,%20%09%09%09.base-evaluation%20td%20%7B%20%09%09%09%09font-size:%2012px;%20%09%09%09%09/*%20border:%201px%20solid%20%23dcdcdc;%20*/%20%09%09%09%09padding:%201em;%20%09%09%09%7D%20%20%09%09%09@page%20%7B%20%09%09%09%09size:%20A4%20portrait;%20%09%09%09%09margin:%2030px;%20%09%09%09%09margin-top:%20130px;%20%09%09%09%7D%20%20%09%09%09.mate-pro%20%7B%20%09%09%09%09page:%20matePro;%20%09%09%09%7D%20%20%09%09%09.mate-pro-header%20%7B%20%09%09%09%09position:%20running(mateproHeaderRunning);%20%09%09%09%7D%20%20%09%09%09.mate-pro-footer%20%7B%20%09%09%09%09position:%20running(mateproFooterRunning);%20%09%09%09%7D%20%09%09%09.imgSmall%7B%20%09%09%09%09width:180px;%20%7D%20%09%09.imgSmall%3Eimg%7B%20display:%20block%20!important;%20%20%20%20%20%20%20%20%20%20%20width:%20100%25;%20%20%20%20%20%20%20%20%20%20%20height:%20100%25;%20%20%20%20%20%20%20%20%20%20%20object-fit:%20contain;%20%7D%20%20%09%09%09@page%20matePro%20%7B%20%09%09%09%09@top-center%20%7B%20%09%09%09%09%09content:%20element(mateproHeaderRunning);%20%09%09%09%09%7D%20%20%09%09%09%09@bottom-center%20%7B%20%09%09%09%09%09content:%20element(mateproFooterRunning);%20%09%09%09%09%7D%20%20%09%09%09%09@bottom-left%20%7B%20%09%09%09%09%09content:%20counter(page)%20'page,%20total:'%20counter(pages)%20'pages';%20%09%09%09%09%7D%20%09%09%09%7D%20%09%09%3C/style%3E%20%09%3C/head%3E%20%20%09%3Cbody%3E%20%09%09%3Csection%20class=%22mate-pro%22%3E%20%09%09%09%3Cheader%20class=%22base-header%20mate-pro-header%22%3E%20%09%09%09%09%3Cspan%20class=%22base-title%22%3EHUAWEI%20Mate%2060%20Pro%3C/span%3E%20%09%09%09%3C/header%3E%20%20%09%09%09%3Cfooter%20class=%22base-footer%20mate-pro-footer%22%3Efooter%20mate%2060%20pro%3C/footer%3E%20%09%09%09%3Ctable%20class=%22base-evaluation%22%3E%20%09%09%09%09%3Cthead%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Cth%20rowspan=%222%22%20style=%22width:%206%25%22%3E%E5%BA%8F%E5%8F%B7%3Cbr%20/%3EItem%3C/th%3E%20%09%09%09%09%09%09%3Cth%20rowspan=%222%22%20style=%22width:%2051%25%22%3E%E9%A1%B9%E7%9B%AE%E5%86%85%E5%AE%B9%3Cbr%20/%3EDescription%3C/th%3E%20%09%09%09%09%09%09%3Cth%20colspan=%225%22%3EHour%3C/th%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Cth%3ENormal%3C/th%3E%20%09%09%09%09%09%09%3Cth%3EO/T%201%3C/th%3E%20%09%09%09%09%09%09%3Cth%3EO/T%202%3C/th%3E%20%09%09%09%09%09%09%3Cth%20colspan=%222%22%3ETravel/Waiting%3C/th%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%3C/thead%3E%20%20%09%09%09%09%3Ctbody%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E1%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E2%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E3%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E4%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E5%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E6%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E7%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E2%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3Cdiv%20%20class=%22imgSmall%22%3E%3Cimg%20src=%22https://gimg2.baidu.com/image_search/src=http%253A%252F%252Fci.xiaohongshu.com%252Fad604a6f-f140-3777-91a9-c7d225586199%253FimageView2%252F2%252Fw%252F1080%252Fformat%252Fjpg%26refer=http%253A%252F%252Fci.xiaohongshu.com%26app=2002%26size=f9999,10000%26q=a80%26n=0%26g=0n%26fmt=auto?sec=1717903413%26t=cbf606cb221ba4bd391d4ddda999d280%22%20%20/%3E%3C/div%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E3%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3Cdiv%20class=%22imgSmall%22%20%3E%3Cimg%20src=%22https://gimg2.baidu.com/image_search/src=http%253A%252F%252Fci.xiaohongshu.com%252Fad604a6f-f140-3777-91a9-c7d225586199%253FimageView2%252F2%252Fw%252F1080%252Fformat%252Fjpg%26refer=http%253A%252F%252Fci.xiaohongshu.com%26app=2002%26size=f9999,10000%26q=a80%26n=0%26g=0n%26fmt=auto?sec=1717903413%26t=cbf606cb221ba4bd391d4ddda999d280%22%20/%3E%3C/div%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E4%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3Cdiv%20%20class=%22imgSmall%22%3E%3Cimg%20src=%22https://gimg2.baidu.com/image_search/src=http%253A%252F%252Fci.xiaohongshu.com%252Fad604a6f-f140-3777-91a9-c7d225586199%253FimageView2%252F2%252Fw%252F1080%252Fformat%252Fjpg%26refer=http%253A%252F%252Fci.xiaohongshu.com%26app=2002%26size=f9999,10000%26q=a80%26n=0%26g=0n%26fmt=auto?sec=1717903413%26t=cbf606cb221ba4bd391d4ddda999d280%22%20/%3E%3C/div%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E5%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3Cdiv%20class=%22imgSmall%22%20%3E%3Cimg%20src=%22https://gimg2.baidu.com/image_search/src=http%253A%252F%252Fci.xiaohongshu.com%252Fad604a6f-f140-3777-91a9-c7d225586199%253FimageView2%252F2%252Fw%252F1080%252Fformat%252Fjpg%26refer=http%253A%252F%252Fci.xiaohongshu.com%26app=2002%26size=f9999,10000%26q=a80%26n=0%26g=0n%26fmt=auto?sec=1717903413%26t=cbf606cb221ba4bd391d4ddda999d280%22%20%20/%3E%3C/div%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E6%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E7%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E8%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E9%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%20%09%09%09%09%09%09%09%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E1%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E2%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E3%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E4%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E5%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3E%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%20%09%09%09%09%09%3Ctr%3E%20%09%09%09%09%09%09%3Ctd%3E6%3C/td%3E%20%09%09%09%09%09%09%3Ctd%3Efffff%3C/td%3E%20%09%09%09%09%09%09%3Ctd%20colspan=%225%22%3E%20%09%09%09%09%09%09%09%09%09%09%09%09%09%3C/td%3E%20%09%09%09%09%09%3C/tr%3E%20%09%09%09%09%3C/tbody%3E%20%09%09%09%3C/table%3E%20%09%09%3C/section%3E%20%09%3C/body%3E%20%3C/html%3E)
[code.txt](https://github.com/vivliostyle/vivliostyle.js/files/15270044/code.txt)

**Comment by MurakamiShinyu** [comment]
@jiang0112 Thanks for adding test cases to the issue.

The flexbox case is a known issue. See: https://github.com/vivliostyle/vivliostyle.js/issues/594

The table case seems to be a bug. I will investigate it.

**Comment by EnochGao** [comment]
Have a plan?

**Comment by MurakamiShinyu** [comment]
> Have a plan?

I want to make Vivliostyle better, so I want to fix bugs as much as possible. But my time and ability are limited, so I need to prioritize my efforts.

The bug on inline images probably won't take too long to fix, and I can include the fix in the next Vivliostyle.js release (v2.30.0). I would also like to fix bugs on tables, but that may be more complicated.

Which bugs would you like us to fix first?

**Comment by EnochGao** [comment]
> > Have a plan?
> 
> I want to make Vivliostyle better, so I want to fix bugs as much as possible. But my time and ability are limited, so I need to prioritize my efforts.
> 
> The bug on inline images probably won't take too long to fix, and I can include the fix in the next Vivliostyle.js release (v2.30.0). I would also like to fix bugs on tables, but that may be more complicated.
> 
> Which bugs would you like us to fix first?

Thank you for your response. Indeed, it's a remarkable project. I noticed that issue #594 has been open for quite some time, which prompted my inquiry about the roadmap. Currently, the challenges we're facing, particularly, are issues #1330, #1326, #1325, #1324, and #1319.

**Comment by EnochGao** [comment]
> > Have a plan?
> 
> I want to make Vivliostyle better, so I want to fix bugs as much as possible. But my time and ability are limited, so I need to prioritize my efforts.
> 
> The bug on inline images probably won't take too long to fix, and I can include the fix in the next Vivliostyle.js release (v2.30.0). I would also like to fix bugs on tables, but that may be more complicated.
> 
> Which bugs would you like us to fix first?

I am more than willing to make a personal donation, albeit a modest one, to support the cause. However, being located in China, I'm encountering some difficulties with the payment methods. I'll look into it further and see if there's a feasible solution.

**Comment by MurakamiShinyu** [comment]
@EnochGao Thank you very much for the donation via GitHub Sponsors (https://github.com/sponsors/vivliostyle) ❤️

Your contribution is very valuable and I would like to have a good collaboration with you. Did you get my email (from murakami@vivliostyle.org) last night? (I sent to your email address found in https://github.com/EnochGao)

**Comment by EnochGao** [comment]
I apologize, I have just become aware that the email was filtered and not flagged for my attention, which resulted in a delayed response.

**Comment by MurakamiShinyu** [comment]
PR #1333 fixes the bug that inline images cannot be paginated.

Test: https://vivliostyle-git-fix-issue1319-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/42207d7dc720ec7bc81ba7e3fcf97966/raw/issue1319-images-cannot-be-paginated.html

Other cases reported in comments https://github.com/vivliostyle/vivliostyle.js/issues/1319#issuecomment-2102082859 and https://github.com/vivliostyle/vivliostyle.js/issues/1319#issuecomment-2103796868 are separate issues, 
- #594

and probably,
- #1326

**Comment by MurakamiShinyu** [comment]
The case reported in comment https://github.com/vivliostyle/vivliostyle.js/issues/1319#issuecomment-2103796868 moved to the new issue:

- #1335 

and resolved in PR

- #1336
